name: flat
on:
  schedule:
    - cron: 35 21 * * *
  workflow_dispatch:
jobs:
  downloadFromApi:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno ğŸ–¥ï¸
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo âœ…
        uses: actions/checkout@v2
      - name: Fetch data ğŸ“•
        uses: githubocto/flat@v3
        with:
          http_url: https://api.esios.ree.es/archives/70/download_json
          downloaded_filename: price.json
          postprocess: postprocess.js