name: flat
on:
  workflow_dispatch:
  schedule:
    - cron: 35 21 * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno ğŸ–¥ï¸
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo âœ…
        uses: actions/checkout@v2
      - name: Fetch data ğŸ“•
        uses: githubocto/flat@v3
        with:
          http_url: https://api.esios.ree.es/archives/70/download_json
          downloaded_filename: price.json
          postprocess: postprocess.js
      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist